apiVersion: v1
data:
  MYSQL_DATABASE: ZHJ1cGFs
  MYSQL_PASSWORD: cGFzc3dvcmQ=
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=
  MYSQL_USER: dXNlcg==
kind: Secret
metadata:
  creationTimestamp: null
  name: drupal-secret
